;;; canvas-video-test.el --- Native integration tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'canvas-video)
(canvas-video--load-module)

(defconst canvas-video-test--fixture
  (expand-file-name "fixture.mkv" (file-name-directory load-file-name)))

(defun canvas-video-test--wait (predicate)
  (let ((deadline (+ (float-time) 5)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (sleep-for 0.02))
    (should (funcall predicate))))

(ert-deftest canvas-video-native-canvas-and-lifecycle ()
  (let* ((player (canvas-video--native-create 320 180 "null"))
         (canvas (list 'image :type 'canvas :id (make-symbol "test")
                       :data-width 320 :data-height 180)))
    (unwind-protect
        (progn
          (canvas-video--native-command
           player (vector "loadfile" canvas-video-test--fixture "replace"))
          (canvas-video-test--wait
           (lambda () (> (plist-get (canvas-video--native-status player) :frames) 2)))
          (should (canvas-video--native-present player canvas))
          (canvas-refresh canvas)
          (should-error
           (canvas-video--native-present
            player (list 'image :type 'canvas :id 'wrong-size
                         :data-width 319 :data-height 180)))
          (should-error (canvas-video--native-command player ["set" 42]))
          (should-error (canvas-video--native-command player ["loadfile" "a\0b"]))
          (should-error (canvas-video--native-command player [])))
      (canvas-video--native-close player)
      (canvas-video--native-close player))
    (should-error (canvas-video--native-status player))))

(ert-deftest canvas-video-native-rejects-invalid-input ()
  (should-error (canvas-video--native-create -1 180 "null"))
  (should-error (canvas-video--native-create 100 99999999999999999999 nil))
  (should-error (canvas-video--native-create "320" 180 nil))
  (should-error (canvas-video--native-close 42)))

(ert-deftest canvas-video-clock ()
  (should (equal (canvas-video--clock -1) "--:--"))
  (should (equal (canvas-video--clock 65.8) "01:05"))
  (should (equal (canvas-video--clock 3661) "1:01:01")))

(ert-deftest canvas-video-progress-target-and-bounds ()
  (with-temp-buffer
    (let* ((first (canvas-video--make-instance
                   :buffer (current-buffer) :status '(:duration 100)))
           (second (canvas-video--make-instance :buffer (current-buffer)))
           (canvas-video--instances (list first second))
           (canvas-video--dedicated second)
           calls)
      (cl-letf (((symbol-function 'canvas-video-seek-to)
                 (lambda (seconds)
                   (push (list (canvas-video--current) seconds) calls))))
        (canvas-video--seek-fraction first 0.25)
        (canvas-video--seek-fraction first -0.1)
        (canvas-video--seek-fraction first 1.1)
        (should (equal (mapcar #'cadr (reverse calls)) '(25.0 0.0 100.0)))
        (should (cl-every (lambda (call) (eq (car call) first)) calls))
        (should-error (canvas-video--seek-fraction second 0.5) :type 'user-error)
        (setq canvas-video--instances (list second))
        (should-error (canvas-video--seek-fraction first 0.5) :type 'user-error)))))

(ert-deftest canvas-video-speed-menu-target-choices-and-cancel ()
  (with-temp-buffer
    (insert "x")
    (let* ((first (canvas-video--make-instance
                   :buffer (current-buffer) :overlay (make-overlay 1 2)
                   :width 480 :player t :status '(:speed 1.25)))
           (second (canvas-video--make-instance :buffer (current-buffer)))
           (canvas-video--instances (list first second))
           (canvas-video--dedicated second)
           (choice 1.5) menu calls)
      (canvas-video--update-controls first)
      (let* ((text (overlay-get (canvas-video--instance-overlay first) 'after-string))
             (offset (text-property-any 0 (length text) 'canvas-video-command
                                        #'canvas-video-speed-menu text))
             (button (lookup-key (get-text-property offset 'keymap text) [mouse-1])))
        (should (string-match-p "1\\.25x" text))
        (cl-letf (((symbol-function 'x-popup-menu)
                   (lambda (_position items) (setq menu items) choice))
                  ((symbol-function 'canvas-video--send)
                   (lambda (target &rest args) (push (cons target args) calls))))
          (funcall button nil)
          (should (equal (mapcar #'cdr (cdr (cadr menu))) '(1 1.25 1.5 2)))
          (should (equal (car (nth 1 (cdr (cadr menu)))) "✓  1.25x"))
          (should (equal calls (list (list first "set" "speed" "1.5"))))
          (setq choice nil)
          (funcall button nil)
          (should (= (length calls) 1)))))))

(defun canvas-video-test--insert (&optional source)
  "Use real libmpv and canvas with only the GUI requirement stubbed in batch."
  (let ((canvas-video-audio-output "null"))
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t)))
      (canvas-video-insert (or source canvas-video-test--fixture) 320 180))))

(defun canvas-video-test--status (instance)
  (canvas-video--native-status (canvas-video--instance-player instance)))

(ert-deftest canvas-video-resize-preserves-player-pixels-and-document ()
  (with-temp-buffer
    (let* ((first (canvas-video-test--insert))
           (_ (insert "\n"))
           (second (canvas-video-test--insert))
           (player (canvas-video--instance-player first))
           (canvas (canvas-video--instance-canvas first)))
      (canvas-video-test--wait
       (lambda () (> (plist-get (canvas-video-test--status first) :frames) 2)))
      (canvas-video--send first "set" "pause" "yes")
      (canvas-video-test--wait
       (lambda () (plist-get (canvas-video-test--status first) :paused)))
      (set-buffer-modified-p nil)
      (let ((text (buffer-string))
            (tick (buffer-chars-modified-tick))
            (position (plist-get (canvas-video-test--status first) :position)))
        (canvas-video--set-display-scale first 1.5)
        (should (= 1.5 (canvas-video--display-scale first)))
        (should (= 1.0 (canvas-video--display-scale second)))
        (should (eq player (canvas-video--instance-player first)))
        (should (eq canvas (canvas-video--render-canvas first)))
        (should-not (eq canvas (canvas-video--instance-canvas first)))
        (should (= 320 (plist-get (cdr canvas) :data-width)))
        (should (= 180 (plist-get (cdr canvas) :data-height)))
        (let ((display (canvas-video--instance-canvas first)))
          (should (= 480 (plist-get (cdr display) :data-width)))
          (should (= 270 (plist-get (cdr display) :data-height)))
          (should (= 1.0 (plist-get (cdr display) :scale))))
        (should (plist-get (canvas-video-test--status first) :paused))
        (should (= position (plist-get (canvas-video-test--status first) :position)))
        (should (equal text (buffer-string)))
        (should (= tick (buffer-chars-modified-tick)))
        (should-not (buffer-modified-p)))
      ;; A new video frame must enter the original canvas and then be scaled
      ;; into the visible canvas.  Merely testing image-size misses NS's bug.
      (let ((present (symbol-function 'canvas-video--native-present))
            (scale (symbol-function 'canvas-video--native-scale)) scaled)
        (cl-letf (((symbol-function 'canvas-video--visible-p) (lambda (_) t))
                  ((symbol-function 'canvas-video--native-present)
                   (lambda (p destination)
                     (when (eq p player) (should (eq destination canvas)))
                     (funcall present p destination)
                     t))
                  ((symbol-function 'canvas-video--native-scale)
                   (lambda (source destination)
                     (push (list source destination) scaled)
                     (funcall scale source destination))))
          (canvas-video--tick (current-buffer)))
        (should (equal scaled (list (list canvas (canvas-video--instance-canvas first)))))
        (should (eq player (canvas-video--instance-player first))))
      ;; Display resizing remains valid even when the native player is stopped.
      (canvas-video--close-player first)
      (canvas-video--set-display-scale first -10)
      (should (= 0.75 (canvas-video--display-scale first)))
      (canvas-video--set-display-scale first 100)
      (should (= 4096 (round (* 320 (canvas-video--display-scale first))))))))

(ert-deftest canvas-video-native-scale-validation ()
  (let ((source (list 'image :type 'canvas :id 'scale-source
                      :data-width 2 :data-height 2 :data [4294901760 4278255360 4278190335 4294967295]))
        (destination (list 'image :type 'canvas :id 'scale-destination
                           :data-width 4 :data-height 4)))
    (should (canvas-video--native-scale source destination))
    (should-error (canvas-video--native-scale source source))
    (should-error (canvas-video--native-scale nil destination))
    (setf (plist-get (cdr destination) :data-width) 4097)
    (should-error (canvas-video--native-scale source destination))))

(ert-deftest canvas-video-resize-drag-axes-release-and-target ()
  (with-temp-buffer
    (let* ((first (canvas-video-test--insert))
           (_ (insert "\n"))
           (second (canvas-video-test--insert))
           (window (selected-window))
           (start (list window 1 '(100 . 100) 0))
           (end (list window 1 '(100 . 190) 0))
           (controls (overlay-get (canvas-video--instance-overlay first) 'after-string))
           (offset (text-property-any 0 (length controls) 'canvas-video-command
                                      'canvas-video--drag-resize controls))
           (handler (lookup-key (get-text-property offset 'keymap controls) [down-mouse-1]))
           (events (list (list 'mouse-movement end)
                         (list 'drag-mouse-1 start end)))
           (unread-command-events nil))
      (goto-char (overlay-start (canvas-video--instance-overlay second)))
      (cl-letf (((symbol-function 'read-event) (lambda (&rest _) (pop events))))
        (funcall handler (list 'down-mouse-1 start)))
      (should (= 1.5 (canvas-video--display-scale first)))
      (should (= 1.0 (canvas-video--display-scale second)))
      (should-not events)
      (should-not unread-command-events)
      ;; A horizontal drag changes width by exactly its pixel delta.  An
      ;; unrelated key exits tracking and is returned to the command loop.
      (setq events (list (list 'mouse-movement
                               (list window 1 '(20 . 100) 0)) ?a))
      (cl-letf (((symbol-function 'read-event) (lambda (&rest _) (pop events))))
        (funcall handler (list 'down-mouse-1 start)))
      (should (= 1.25 (canvas-video--display-scale first)))
      (should (equal unread-command-events '(?a))))))

(ert-deftest canvas-video-inline-mixed-content-and-independent-controls ()
  (with-temp-buffer
    (text-mode)
    (insert "Introduction\n")
    (let* ((image (create-image (make-vector 4 #xFFFF0000) 'canvas t
                                :data-width 2 :data-height 2))
           (image-start (point))
           (_ (insert-image image "[picture]"))
           (displayed-image (get-text-property image-start 'display))
           (first (canvas-video-test--insert))
           (_ (insert "\nBetween the videos\n"))
           (second (canvas-video-test--insert)))
      (insert "\nConclusion\n")
      (should (eq major-mode 'text-mode))
      (should-not buffer-read-only)
      (should (eq (get-text-property image-start 'display) displayed-image))
      (should (= (length canvas-video--instances) 2))
      (should-not (eq (canvas-video--instance-player first)
                      (canvas-video--instance-player second)))
      (canvas-video-test--wait
       (lambda () (and (> (plist-get (canvas-video-test--status first) :frames) 2)
                       (> (plist-get (canvas-video-test--status second) :frames) 2))))
      ;; While point is on the second video, the first video's button must
      ;; still pause only the first.  Call the actual after-string keymap.
      (goto-char (overlay-start (canvas-video--instance-overlay second)))
      (let* ((controls (overlay-get (canvas-video--instance-overlay first) 'after-string))
             (offset (text-property-any 0 (length controls) 'canvas-video-command
                                        #'canvas-video-toggle-pause controls))
             (map (get-text-property offset 'keymap controls)))
        (funcall (lookup-key map [mouse-1]) nil))
      (canvas-video-test--wait
       (lambda () (plist-get (canvas-video-test--status first) :paused)))
      (should-not (plist-get (canvas-video-test--status second) :paused))
      (canvas-video-seek-to 2.5)
      (canvas-video-test--wait
       (lambda () (> (plist-get (canvas-video-test--status second) :position) 2.4)))
      (should (< (plist-get (canvas-video-test--status first) :position) 1.5))
      ;; Timer refreshes are display changes, not document edits/undo entries.
      (set-buffer-modified-p nil)
      (let ((text (buffer-string)) (tick (buffer-chars-modified-tick))
            (undo buffer-undo-list))
        (canvas-video--tick (current-buffer))
        (should (equal text (buffer-string)))
        (should (= tick (buffer-chars-modified-tick)))
        (should (eq undo buffer-undo-list))
        (should-not (buffer-modified-p)))
      ;; Regular editing outside the video retains the major mode bindings.
      (goto-char (point-min))
      (should (eq (key-binding (kbd "SPC")) 'self-insert-command))
      (should (eq (key-binding (kbd "C-c C-v SPC")) 'canvas-video-toggle-pause))
      (should-error (canvas-video-toggle-pause) :type 'user-error)
      (insert "Edited text\n")
      (should (= (length canvas-video--instances) 2)))))

(ert-deftest canvas-video-inline-boundaries-delete-and-undo ()
  (with-temp-buffer
    (buffer-enable-undo)
    (insert "Before\n")
    (let* ((first (canvas-video-test--insert))
           (overlay (canvas-video--instance-overlay first))
           (player (canvas-video--instance-player first)))
      (goto-char (overlay-start overlay))
      (insert "Left edge\n")
      (should (canvas-video--intact-p first))
      (goto-char (overlay-end overlay))
      (insert "\nRight edge\n")
      (should (canvas-video--intact-p first))
      (let ((second (canvas-video-test--insert))
            (timer canvas-video--timer))
        (undo-boundary)
        (delete-region (overlay-start overlay) (overlay-end overlay))
        (should-not (overlay-buffer overlay))
        (should-error (canvas-video--native-status player))
        (should (= (length canvas-video--instances) 1))
        (should (memq timer timer-list))
        ;; Undo restores plain text, never an orphaned running decoder.
        (let ((undo-in-progress t)) (primitive-undo 1 buffer-undo-list))
        (should (= (length canvas-video--instances) 1))
        (should (canvas-video--instance-player second))
        (goto-char (overlay-start (canvas-video--instance-overlay second)))
        (canvas-video-remove)
        (should-not canvas-video--instances)
        (should-not (memq timer timer-list))
        (should (string-match-p "Before\nLeft edge" (buffer-string)))))))

(ert-deftest canvas-video-inline-edit-placeholder-and-external-overlay-removal ()
  (with-temp-buffer
    (let* ((first (canvas-video-test--insert))
           (player (canvas-video--instance-player first)))
      (goto-char (1+ (overlay-start (canvas-video--instance-overlay first))))
      (insert "changed")
      (should-not canvas-video--instances)
      (should-error (canvas-video--native-status player)))
    (goto-char (point-max))
    (let* ((second (canvas-video-test--insert))
           (player (canvas-video--instance-player second)))
      (delete-overlay (canvas-video--instance-overlay second))
      (canvas-video--tick (current-buffer))
      (should-not canvas-video--instances)
      (should-error (canvas-video--native-status player)))))

(ert-deftest canvas-video-inline-stop-replay-and-mode-cleanup ()
  (with-temp-buffer
    (text-mode)
    (let* ((first (canvas-video-test--insert))
           (second (canvas-video-test--insert))
           (old-player (canvas-video--instance-player first)))
      (canvas-video--invoke first #'canvas-video-stop)
      (should-not (canvas-video--instance-player first))
      (should (canvas-video--instance-player second))
      (should-error (canvas-video--native-status old-player))
      (canvas-video--invoke first #'canvas-video-toggle-pause)
      (should (canvas-video--instance-player first))
      (should-not (eq old-player (canvas-video--instance-player first)))
      (let ((p1 (canvas-video--instance-player first))
            (p2 (canvas-video--instance-player second))
            (timer canvas-video--timer))
        (fundamental-mode)
        (should-not canvas-video--instances)
        (should-not (memq timer timer-list))
        (should-error (canvas-video--native-status p1))
        (should-error (canvas-video--native-status p2))))))

(ert-deftest canvas-video-inline-disable-and-kill-buffer ()
  (let ((buffer (generate-new-buffer " *inline-video-test*")))
    (unwind-protect
        (with-current-buffer buffer
          (let* ((instance (canvas-video-test--insert))
                 (player (canvas-video--instance-player instance))
                 (text (buffer-string)))
            (canvas-video-inline-mode -1)
            (should-not canvas-video--instances)
            (should (equal text (buffer-string)))
            (should-error (canvas-video--native-status player)))
          (let* ((instance (canvas-video-test--insert))
                 (player (canvas-video--instance-player instance))
                 (timer canvas-video--timer))
            (kill-buffer buffer)
            (should-not (memq timer timer-list))
            (should-error (canvas-video--native-status player))))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest canvas-video-inline-load-failure-is-isolated ()
  (with-temp-buffer
    (let* ((good (canvas-video-test--insert))
           (bad (let ((canvas-video-audio-output "null"))
                  (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t)))
                    (canvas-video-insert-url "file:///nonexistent/canvas-video-test.mkv" 320 180)))))
      (canvas-video-test--wait
       (lambda ()
         (setf (canvas-video--instance-next-status bad) 0)
         (canvas-video--tick (current-buffer))
         (not (canvas-video--instance-player bad))))
      (should (stringp (plist-get (canvas-video--instance-status bad) :error)))
      (should (canvas-video--instance-player good))
      (should (timerp canvas-video--timer)))))

(ert-deftest canvas-video-inline-read-only-and-narrowing ()
  (with-temp-buffer
    (insert "Paragraph\n")
    (let* ((instance (canvas-video-test--insert))
           (overlay (canvas-video--instance-overlay instance))
           (text (buffer-string)))
      (setq buffer-read-only t)
      (goto-char (overlay-start overlay))
      (should-error (canvas-video-remove) :type 'buffer-read-only)
      (should-error (canvas-video-test--insert) :type 'buffer-read-only)
      (should (equal text (buffer-string)))
      (should (canvas-video--instance-player instance))
      (setq buffer-read-only nil)
      (narrow-to-region (point-min) 5)
      (canvas-video--tick (current-buffer))
      (should (canvas-video--instance-player instance))
      (widen))))

(ert-deftest canvas-video-inline-creation-failure-rolls-back-text ()
  (with-temp-buffer
    (insert "Unchanged")
    (cl-letf (((symbol-function 'canvas-video--native-create)
               (lambda (&rest _) (error "Creation failed"))))
      (should-error (canvas-video-test--insert)))
    (should (equal (buffer-string) "Unchanged"))
    (should-not canvas-video--instances)
    (should-not canvas-video--timer)))
