;;; canvas-video-volume-test.el --- Slider interactions -*- lexical-binding: t; -*-
(require 'ert)
(require 'canvas-video-volume)

(ert-deftest canvas-video-volume-drag-target-bounds-and-release ()
  (with-temp-buffer
    (let* ((instance (canvas-video--make-instance :buffer (current-buffer) :player t))
           (other (canvas-video--make-instance :buffer (current-buffer) :player t))
           (canvas-video--instances (list instance other))
           (canvas-video--dedicated other)
           (canvas-video-volume--instance instance)
           (events '((switch-frame nil) (mouse-movement -30)
                     (select-window nil) (mouse-movement 300) (drag-mouse-1 130)))
           calls)
      (cl-letf (((symbol-function 'posn-object-x-y) (lambda (_) '(20 . 50)))
                ((symbol-function 'canvas-video-volume--event-x) #'cadr)
                ((symbol-function 'read-event) (lambda (&rest _) (pop events)))
                ((symbol-function 'canvas-video-volume--draw) #'ignore)
                ((symbol-function 'canvas-video-volume--live-p) (lambda () nil))
                ((symbol-function 'canvas-video--send)
                 (lambda (target &rest args) (push (cons target args) calls))))
        (canvas-video-volume--drag
         '(down-mouse-1 (nil 1 (20 . 50) 0 nil nil (20 . 50) 0 (20 . 50) (260 . 76))))
        (should-not events)
        (should (cl-every (lambda (call) (eq (car call) instance)) calls))
        (should (equal (mapcar #'cdr (reverse calls))
                       '(("set" "volume" "0") ("set" "mute" "no")
                         ("set" "volume" "0") ("set" "mute" "no")
                         ("set" "volume" "100") ("set" "mute" "no")
                         ("set" "volume" "50") ("set" "mute" "no"))))
        (setq canvas-video--instances (list other))
        (should-error (canvas-video-volume--set-at instance 130) :type 'user-error)))))

(ert-deftest canvas-video-volume-dismiss-and-cleanup ()
  (let* ((buffer (generate-new-buffer " *volume-test*"))
         (canvas-video-volume--buffer buffer)
         (canvas-video-volume--frame nil)
         (canvas-video-volume--timer (run-at-time 60 nil #'ignore))
         (timer canvas-video-volume--timer)
         (canvas-video-volume--exit nil)
         (last-input-event 'escape))
    (unwind-protect
        (progn
          (canvas-video-volume--dismiss)
          (should-not (buffer-live-p buffer))
          (should-not (memq timer timer-list))
          (canvas-video-volume-hide))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (cancel-timer timer))))

(ert-deftest canvas-video-volume-frame-switch-before-click ()
  (let ((canvas-video-volume--frame (selected-frame)) hidden)
    (cl-letf (((symbol-function 'canvas-video-volume-hide)
               (lambda () (setq hidden t))))
      (dolist (event `((switch-frame ,(selected-frame))
                      (select-window ,(selected-window))
                      (down-mouse-1 (,(selected-window) 1 (20 . 50) 0))))
        (let ((last-input-event event)) (canvas-video-volume--dismiss))
        (should-not hidden))
      (let ((last-input-event 'escape)) (canvas-video-volume--dismiss))
      (should hidden))))
